#!/usr/bin/env python3
"""Honest routers: can device-visible features pick the preset per clip?

Two routers, both trained on measured per-preset gains and both seeing only
what the device sees:

  * **classify -> table**: multinomial logistic predicts the shift kind; the
    per-kind preset table is applied to the predicted label.
  * **gain regression -> argmax**: ridge predicts each preset's gain
    directly; apply the per-clip argmax. Ceiling is the per-clip oracle.

Two evaluation modes:

  * default — 5-fold CV inside one npz (router AND presets fit on train
    folds). Fine for a first look, but the router then trains on ~120 clips
    drawn from the same pool it is scored on.
  * `--train-npz` — fit everything ONCE on a separate pool (generated by
    `mixed_adapt_eval.py --pool train`, i.e. VBD *train* utterances) and
    evaluate ONCE on the test npz. The deployable configuration, and the
    honest one for a paper.

The feature set is classical DSP over the input STFT plus the enhancer's own
behaviour. The reverb-sensitive block (sub-band envelope decay, late/early
energy, envelope kurtosis, centroid dynamics) exists because measured rooms
proved subtler than synthetic tails: the first feature set detected
synthetic reverb at 87% but real reverb at only 61%.

    python knob_router.py --npz artifacts/mixed_shift_realrir.npz \\
        --train-npz artifacts/mixed_train_pool_realrir.npz --rir-dir <dir>
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np
import torch

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parents[1] / "src"))

import dsp  # noqa: E402
from adapter_adapt_eval import si_snr  # noqa: E402
from convfsenet_arch import build_split  # noqa: E402
import mixed_adapt_eval as mx  # noqa: E402
from mixed_adapt_eval import SHIFTS, apply_shift, load_train_pairs  # noqa: E402
from pesq_adapt_eval import load_test_pairs  # noqa: E402

FEAT_NAMES = ("decay1", "decay4", "mod_depth", "snr_est", "tilt", "highband",
              "rolloff", "floor_tilt", "floor_level", "hf_floor",
              "m_mean", "m_std", "sisnr0",
              "dec_low", "dec_mid", "dec_high", "late_early", "env_kurt",
              "cent_std")


def features(inp: np.ndarray, m0: torch.Tensor, sisnr0: float) -> np.ndarray:
    X = dsp.stft(inp / (np.sqrt(np.mean(inp ** 2)) + 1e-12))
    P = np.abs(X) ** 2                                    # [F, T]
    F_, T = P.shape

    lenv = 10 * np.log10(P.sum(axis=0) + 1e-12)
    lenv = lenv - lenv.mean()

    def ac(v, lag):
        return float(np.corrcoef(v[:-lag], v[lag:])[0, 1])
    decay1, decay4 = ac(lenv, 1), ac(lenv, 4)
    mod_depth = float(lenv.std())

    # minimum-statistics noise floor, per band
    S = np.empty_like(P)
    S[:, 0] = P[:, 0]
    for t in range(1, T):
        S[:, t] = 0.8 * S[:, t - 1] + 0.2 * P[:, t]
    w = 47
    floor = np.stack([S[:, max(0, t - w + 1): t + 1].min(axis=1)
                      for t in range(T)], axis=1)
    fmean = floor.mean(axis=1)
    snr_est = float(10 * np.log10(P.mean() / max(fmean.mean(), 1e-12)))
    floor_level = float(10 * np.log10(fmean.mean() + 1e-12)
                        - 10 * np.log10(P.mean() + 1e-12))
    fr = np.arange(F_) / F_
    floor_tilt = float(np.polyfit(fr, 10 * np.log10(fmean + 1e-12), 1)[0])

    spec = 10 * np.log10(P.mean(axis=1) + 1e-12)
    tilt = float(np.polyfit(fr, spec, 1)[0])
    k3 = int(3000 / 8000 * F_)
    highband = float(P[k3:].mean() / (P.mean() + 1e-12))
    cum = np.cumsum(P.mean(axis=1))
    rolloff = float(np.searchsorted(cum, 0.95 * cum[-1]) / F_)
    top = fmean[int(0.5 * F_):]
    hf_floor = float(10 * np.log10(top.mean() + 1e-12)
                     - 10 * np.log10(fmean.mean() + 1e-12))

    # ---- reverb-sensitive block ----
    # sub-band envelope decay: reverberant energy lingers in every band
    thirds = np.array_split(np.arange(F_), 3)
    sub = []
    for idx in thirds:
        e = 10 * np.log10(P[idx].sum(axis=0) + 1e-12)
        sub.append(ac(e - e.mean(), 4))
    dec_low, dec_mid, dec_high = map(float, sub)
    # late/early energy after envelope peaks: tails raise it
    env = P.sum(axis=0)
    med = np.median(env)
    peaks = [t for t in range(2, T - 14)
             if env[t] > 4 * med and env[t] == env[t - 2: t + 3].max()]
    if peaks:
        le = [10 * np.log10(env[t + 4: t + 13].mean() / (env[t] + 1e-12) + 1e-12)
              for t in peaks]
        late_early = float(np.mean(le))
    else:
        late_early = -30.0
    # dry speech has a peaky envelope; reverb flattens it
    ec = env / (env.mean() + 1e-12)
    env_kurt = float(((ec - ec.mean()) ** 4).mean()
                     / (((ec - ec.mean()) ** 2).mean() ** 2 + 1e-12))
    # centroid dynamics: smearing slows spectral movement
    cent = (P * fr[:, None]).sum(axis=0) / (P.sum(axis=0) + 1e-12)
    cent_std = float(cent.std())

    return np.array([decay1, decay4, mod_depth, snr_est, tilt, highband,
                     rolloff, floor_tilt, floor_level, hf_floor,
                     float(m0.mean()), float(m0.std()), sisnr0,
                     dec_low, dec_mid, dec_high, late_early, env_kurt,
                     cent_std])


def logistic_fit(X, y, classes, iters=600, lr=0.5):
    n, d = X.shape
    K = len(classes)
    Y = np.zeros((n, K))
    for k, c in enumerate(classes):
        Y[y == c, k] = 1.0
    W = np.zeros((d + 1, K))
    Xb = np.hstack([X, np.ones((n, 1))])
    for _ in range(iters):
        Z = Xb @ W
        Z -= Z.max(axis=1, keepdims=True)
        Pr = np.exp(Z); Pr /= Pr.sum(axis=1, keepdims=True)
        W -= lr * (Xb.T @ (Pr - Y) / n + 1e-3 * W)
    return W


def logistic_predict(W, X, classes):
    Xb = np.hstack([X, np.ones((len(X), 1))])
    return np.array([classes[j] for j in (Xb @ W).argmax(axis=1)])


def compute_features(npz_path: Path, trunk, head, win) -> np.ndarray:
    """Replay an npz's clip generation exactly and compute features."""
    z = np.load(npz_path, allow_pickle=True)
    kinds_ref = z["kinds"]
    n = len(kinds_ref)
    if "meta" in z:
        pool, seconds, seed, clips = (str(z["meta"][0]), int(z["meta"][1]),
                                      int(z["meta"][2]), int(z["meta"][3]))
    else:                                   # legacy npz: the original test run
        pool, seconds, seed, clips = "test", 3, 0, n
    pairs = (load_test_pairs(clips, seconds) if pool == "test"
             else load_train_pairs(clips, seconds, seed=seed + 7))
    rng = np.random.default_rng(seed)
    feats = np.zeros((n, len(FEAT_NAMES)))
    t0 = time.time()
    for i, (cl, no) in enumerate(pairs[:n]):
        kind = SHIFTS[i % len(SHIFTS)]
        assert kind == str(kinds_ref[i]), f"clip order mismatch at {i} in {npz_path}"
        _, inp = apply_shift(cl, no, kind, rng)
        no_s, nf = dsp.rms_normalize(inp)
        X = dsp.stft(no_s)
        Xt = torch.from_numpy(np.abs(X)).float()
        mag = Xt[: trunk.n_features][None]
        with torch.no_grad():
            pad = mag[..., :1].repeat(1, 1, trunk.context_l)
            h = trunk(torch.cat([pad, mag], dim=-1))
            m0 = torch.sigmoid(head.conv(h))[0]
            full = torch.cat([m0, torch.zeros(1, m0.shape[1])], 0)
            y = torch.istft((torch.from_numpy(X).to(torch.complex64) * full)[None],
                            n_fft=dsp.N_FFT, hop_length=dsp.HOP,
                            win_length=dsp.WIN_LENGTH, window=win,
                            length=len(inp), center=True)[0] / nf
            s0 = float(si_snr(y, torch.from_numpy(np.asarray(inp)).float()))
        feats[i] = features(np.asarray(inp), m0, s0)
    print(f"  features for {npz_path.name}: {n} clips in {time.time()-t0:.0f}s")
    return feats


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--npz", type=Path, default=HERE / "artifacts" / "mixed_shift.npz")
    ap.add_argument("--train-npz", type=Path, default=None,
                    help="separate labelled pool to fit on (VBD train split); "
                         "evaluation is then a single held-out pass")
    ap.add_argument("--split", type=Path, default=HERE / "artifacts" / "convfsenet_split.pt")
    ap.add_argument("--folds", type=int, default=5)
    ap.add_argument("--ridge", type=float, default=1.0)
    ap.add_argument("--rir-dir", type=Path, default=None,
                    help="measured RIR bank; must match how the npz was built")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    torch.manual_seed(0); torch.set_num_threads(8)
    if args.rir_dir is not None:
        from real_rir import load_rirs
        mx.RIR_BANK = load_rirs(args.rir_dir)
        print(f"measured RIR bank: {len(mx.RIR_BANK)} impulse responses")

    trunk, head = build_split()
    sp = torch.load(args.split, map_location="cpu", weights_only=False)
    trunk.load_state_dict(sp["trunk"]); head.load_state_dict(sp["head"]); trunk.eval()
    win = torch.from_numpy(dsp.hann_periodic()).float()

    z = np.load(args.npz, allow_pickle=True)
    kinds, g_grid = z["kinds"], z["g_grid"]
    n = len(kinds)
    feats = compute_features(args.npz, trunk, head, win)

    def stat(g):
        se = g.std(ddof=1) / np.sqrt(len(g))
        return f"{g.mean():+8.3f} {1.96*se:8.3f} {(g>0).mean()*100:8.0f}%"

    jbest = int(np.nanmean(g_grid, axis=0).argmax())
    null = g_grid[:, jbest]

    def vs_null(g):
        d = g - null
        se = d.std(ddof=1) / np.sqrt(len(d))
        return f"{d.mean():+8.3f}" + ("*" if abs(d.mean()) > 1.96 * se else "")

    if args.train_npz is not None:
        # ---------- held-out mode: fit once on the pool, evaluate once ----------
        zt = np.load(args.train_npz, allow_pickle=True)
        k_tr, g_tr = zt["kinds"], zt["g_grid"]
        f_tr = compute_features(args.train_npz, trunk, head, win)
        print(f"\nfit on {len(k_tr)} train-pool clips, evaluate on {n} test clips")

        mu, sd = f_tr.mean(0), f_tr.std(0) + 1e-9
        Xtr, Xte = (f_tr - mu) / sd, (feats - mu) / sd

        W = logistic_fit(Xtr, k_tr, SHIFTS)
        pk = logistic_predict(W, Xte, SHIFTS)
        acc = (pk == kinds).mean()
        conf = {k: (pk[kinds == k] == k).mean() for k in SHIFTS}
        print(f"router accuracy: {acc*100:.0f}%  ("
              + ", ".join(f"{k} {v*100:.0f}%" for k, v in conf.items()) + ")")

        table = {k: int(np.nanmean(g_tr[k_tr == k], axis=0).argmax())
                 for k in SHIFTS}
        g_cls = g_grid[np.arange(n), [table[k] for k in pk]]

        Xb = np.hstack([Xtr, np.ones((len(Xtr), 1))])
        B = np.linalg.solve(Xb.T @ Xb + args.ridge * np.eye(Xb.shape[1]),
                            Xb.T @ np.nan_to_num(g_tr))
        pred = np.hstack([Xte, np.ones((n, 1))]) @ B
        g_reg = g_grid[np.arange(n), pred.argmax(axis=1)]

        # the train pool also supplies a fairer global preset (no test fitting)
        j_tr = int(np.nanmean(g_tr, axis=0).argmax())
        g_glob = g_grid[:, j_tr]

        print(f"\n{'method (held-out)':>34} {'gain':>8} {'95% CI':>8} {'improved':>9} {'vs null':>9}")
        print(f"{'global preset (null, test-fit)':>34} {stat(null)} {'—':>9}")
        print(f"{'global preset (train-fit)':>34} {stat(g_glob)} {vs_null(g_glob)}")
        print(f"{'classify -> table':>34} {stat(g_cls)} {vs_null(g_cls)}")
        print(f"{'gain regression -> argmax':>34} {stat(g_reg)} {vs_null(g_reg)}")
        ptab = np.array([g_grid[i, table[str(kinds[i])]] for i in range(n)])
        print(f"{'table with oracle labels':>34} {stat(ptab)} {vs_null(ptab)}")
        print(f"{'per-clip grid oracle':>34} {stat(g_grid.max(1))} {vs_null(g_grid.max(1))}")
        imp = np.abs(B[:-1]).mean(axis=1)
        top = np.argsort(imp)[::-1][:8]
        print("\ntop regressor features: "
              + ", ".join(f"{FEAT_NAMES[j]} {imp[j]:.3f}" for j in top))
        return

    # ---------- CV mode (single npz) ----------
    rng2 = np.random.default_rng(args.seed)
    order = rng2.permutation(n)
    g_cls = np.zeros(n)
    g_reg = np.zeros(n)
    pred_kinds = np.empty(n, dtype=object)
    for f in range(args.folds):
        te = order[f::args.folds]
        tr = np.setdiff1d(order, te)
        mu, sd = feats[tr].mean(0), feats[tr].std(0) + 1e-9
        Xtr, Xte = (feats[tr] - mu) / sd, (feats[te] - mu) / sd
        W = logistic_fit(Xtr, kinds[tr], SHIFTS)
        pk = logistic_predict(W, Xte, SHIFTS)
        pred_kinds[te] = pk
        table = {k: int(np.nanmean(g_grid[tr[kinds[tr] == k]], axis=0).argmax())
                 for k in SHIFTS}
        g_cls[te] = g_grid[te, [table[k] for k in pk]]
        Xb = np.hstack([Xtr, np.ones((len(Xtr), 1))])
        B = np.linalg.solve(Xb.T @ Xb + args.ridge * np.eye(Xb.shape[1]),
                            Xb.T @ g_grid[tr])
        pred = np.hstack([Xte, np.ones((len(Xte), 1))]) @ B
        g_reg[te] = g_grid[te, pred.argmax(axis=1)]

    acc = (pred_kinds == kinds).mean()
    conf = {k: (pred_kinds[kinds == k] == k).mean() for k in SHIFTS}
    print(f"\nrouter accuracy (4-way, CV): {acc*100:.0f}%  ("
          + ", ".join(f"{k} {v*100:.0f}%" for k, v in conf.items()) + ")")
    print(f"\n{'method':>34} {'gain':>8} {'95% CI':>8} {'improved':>9} {'vs null':>9}")
    print(f"{'global preset (null)':>34} {stat(null)} {'—':>9}")
    print(f"{'classify -> table (honest, CV)':>34} {stat(g_cls)} {vs_null(g_cls)}")
    print(f"{'gain regression -> argmax (CV)':>34} {stat(g_reg)} {vs_null(g_reg)}")
    ptab = np.array([g_grid[i, int(np.nanmean(g_grid[kinds == kinds[i]],
                                              axis=0).argmax())] for i in range(n)])
    print(f"{'per-kind table, oracle labels':>34} {stat(ptab)} {vs_null(ptab)}")
    print(f"{'per-clip grid oracle':>34} {stat(g_grid.max(1))} {vs_null(g_grid.max(1))}")


if __name__ == "__main__":
    main()
