#!/usr/bin/env python3
"""Bake VoiceBank-DEMAND clips into loss_input.h for the bare-runtime firmware.

Emits the audio in the *compiled graph's* device layout — `stedgeai` transposes
the rows input to [1, 160, 25], which is not the ONNX layout — so the firmware
can `memcpy` straight into the network's input buffer with no reshaping on the
MCU. Floats are written with an explicit decimal point: `0f` is not a valid C
float literal and the compiler rejects it.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent


def lit(v: float) -> str:
    s = f"{float(v):.9g}"
    if not any(c in s for c in ".eE"):
        s += ".0"
    return s + "f"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--cache", type=Path, default=HERE.parent / "artifacts" / "vbd_cache.npz")
    ap.add_argument("--clips", type=int, nargs="*", default=[12, 30],
                    help="cache indices to bake in (two distinct clips prove "
                         "input-dependence, or its absence)")
    ap.add_argument("--samples", type=int, default=4000, help="0.25 s at 16 kHz")
    ap.add_argument("--rows", type=int, default=25)
    ap.add_argument("--hop", type=int, default=160)
    ap.add_argument("--out", type=Path, default=HERE / "loss_input.h")
    args = ap.parse_args()

    clips = np.load(args.cache)["clips"]
    rows = [clips[i][: args.samples].astype(np.float32)
            .reshape(1, args.rows, args.hop).transpose(0, 2, 1).copy().ravel()
            for i in args.clips]

    lines = [
        "/* Generated by gen_loss_input.py -- VBD clips in the compiled graph's",
        f"   device layout [1,{args.hop},{args.rows}] float32, plus the loss weights. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define LOSS_N_CLIPS {len(rows)}",
        f"#define LOSS_WAV_LEN {rows[0].size}",
        "",
    ]
    for k, r in enumerate(rows):
        lines.append(f"static const float loss_wav_{k}[LOSS_WAV_LEN] = {{")
        for i in range(0, r.size, 8):
            lines.append("  " + ", ".join(lit(v) for v in r[i:i + 8]) + ",")
        lines.append("};")
    lines.append("static const float *const loss_wavs[LOSS_N_CLIPS] = { "
                 + ", ".join(f"loss_wav_{k}" for k in range(len(rows))) + " };")
    lines.append("static const float loss_w[3] = { 0.0f, 0.0f, -1.0f };")
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({args.out.stat().st_size/1e6:.2f} MB, "
          f"clips {args.clips}, {rows[0].size} samples each)")


if __name__ == "__main__":
    main()
